version: '3.8'

services:
  nestjs:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  postgres:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
